#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "click",
# ]
# ///

from app.cli import entry_point

if __name__ == '__main__':
    entry_point()
